### PR TITLE
YLP-173 Loop mode label

### PR DESCRIPTION
**Pull request by yvon-dblg**

### CODE REVIEW

**Review by BigFab — COMMENTED** [review]
Changes look good for me

**Comment by franck-fourel** [comment]
@MarineDBL @yvon-dblg 
image
image

**Review by franck-fourel — CHANGES_REQUESTED** [review]
some general comments on the new widget:
- the bold type of "loop mode off" make it more visible than "loop mode on" which is probably not the goal of this change
- switching to a small screen makes the widget quite different. While the circle is thinner than other lines in standard mode, it's larger on small screen. It looks ok on phone screen.
- The order of the items in the legend is the same as the order in the widget: loop mode off, loop mode on vs loop mode on, loop mode off in the widget. 
- the "on" and "off" items in the legend are not aligned correctly on the legend line.

**Comment by MarineDBL** [comment]
Other changes to make:
- use the same grey for "OFF" and "2" than the one used for the title
- put the "%" in grey, leave the numbers in color
- use the same font-size for the percentages than in the other widgets
- try to use the same width for the arch than in other widgets (see if it works)

**Review by Nas84 — APPROVED** [review]

**Pull request merged**
