### PR TITLE
YLP-2438 Inconsistency in the daily view between carbs displayed on the graph and total carbs in the statistics panel

### PR DESCRIPTION
**Pull request by Xwdrblue**
## Checklist
- [x] PR name contains the Jira ticket number
- [x] Changelog updated
- [x] Code tested (unit tests and integration tests)
- [x] No console errors/warnings in integration tests
- [x] No translation files updated (except for English files)
- [x] Code formatted on every file
- [x] Copyright added on every file
- [x] End-to-end tests successful on CI

### CODE REVIEW

**Review by TimCanu — COMMENTED** [review]
Also worried about conflicts with release branch. Can you compare ppd with this branch? Thanks :slightly_smiling_face:

**Comment by Xwdrblue** [comment]
I wasn't able to take all the modifications that were made in the 3.0.4 release branch, as the changes made in patient-dashboard in particular mean that I'm back to creating several how Data Utile files, so on the Dashboard view the data on the Avg. Daily Total Insulin, Avg. Daily Carbs, Sensor usage will not be equal to that on PPD. The problem will be solved once the release/Un branch has emerged.

**Review by fatb38 — CHANGES_REQUESTED** [review]

**Review by TimCanu — APPROVED** [review]

**Review by TimCanu — APPROVED** [review]

**Pull request merged**
