### PR TITLE
YLP-529 Fix CSS - Yourloops part

### PR DESCRIPTION
**Pull request by yvon-dblg**
Based on blip changes branch

### CODE REVIEW

**Review by franck-fourel — CHANGES_REQUESTED** [review]
couple of things I noticed and that may need @MarineDBL input for some of them:
- team list column titles: MAJ, 16px - X [still 14px]
- Add margin + footer at the end of the page [not done]
- Button “Leave” : color font #DA3A1B (= error snackbar) - done for 'Leave and Delete' but 'Leave' is still green. Is it expected that way ? @MarineDBL 
- Account preferences: title : augment font size + bold - X [which title ??? Update your personal info and preferences is still small] compared to the the other items]
- Breadcrumb: When on homepage, home shouldn’t be clickable. Only when landing on another page - X [what about account prefs ?]

**Comment by MarineDBL** [comment]
> couple of things I noticed and that may need @MarineDBL input for some of them:
> 
> * team list column titles: MAJ, 16px - X [still 14px]
> * Add margin + footer at the end of the page [not done]
> * Button “Leave” : color font #DA3A1B (= error snackbar) - done for 'Leave and Delete' but 'Leave' is still green. Is it expected that way ? @MarineDBL **=> Should be red for all the "warning modal" buttons - I haven't updated the prototypes though**
> * Account preferences: title : augment font size + bold - X [which title ??? Update your personal info and preferences is still small] compared to the the other items] => **this title should be bigger indeed**
> * Breadcrumb: When on homepage, home shouldn’t be clickable. Only when landing on another page - X [what about account prefs ?] => **account pref is a page, so home should be clickable**

**Comment by yvon-dblg** [comment]
> couple of things I noticed and that may need @MarineDBL input for some of them:
> 
>     * team list column titles: MAJ, 16px - X [still 14px]
OK, 16px missing, I will fixed it.

> 
>     * Add margin + footer at the end of the page [not done]

The footer will be done in another PR.

**Review by franck-fourel — COMMENTED** [review]
LGTM but still one question about the Account Preferences breadcrumb
image
- the home is clickable which is fine 
- but why do we keep Account Preferences clickable with a link going to the home. I would propose to remove the Account Preferences link in the BreadCrumb @MarineDBL @yvon-dblg

**Comment by MarineDBL** [comment]
> I would propose to remove the Account Preferences link in the BreadCrumb @MarineDBL @yvon-dblg

I confirm

**Review by franck-fourel — APPROVED** [review]
LGTM

**Pull request merged**
