### PR TITLE
YLP-2634 New behaviour of the care team setting button in the alerts customisation section

### PR DESCRIPTION
**Pull request by TimCanu**
## Checklist
- [x] PR name contains the Jira ticket number
- [x] Changelog updated
- [x] Code tested (unit tests and integration tests)
- [x] No console errors/warnings in integration tests
- [x] No translation files updated (except for English files)
- [x] Code formatted on every file
- [x] Copyright added on every file
- [x] End-to-end tests successful on CI

### CODE REVIEW

**Comment by TimCanu** [comment]
An IT could be added to check the following scenario:
- Patient is not associated to the team values
- The team values are changed to the one of the patient
- Editing the patient should still give the possibility to use the team values

**Review by Nas84 — APPROVED** [review]

**Review by Nas84 — APPROVED** [review]

**Pull request merged**
