### PR TITLE
YLP-2178 Remove redux store

### PR DESCRIPTION
**Pull request by celia-rouis**
## Checklist
- [x] PR name contains the Jira ticket number
- [x] Changelog updated
- [x] Code tested (unit tests and integration tests)
- [x] No console errors/warnings in integration tests
- [x] No translation files updated (except for English files)
- [x] Code formatted on every file
- [x] Copyright added on every file
- [x] End-to-end tests successful on CI

### CODE REVIEW

**Comment by fatb38** [comment]
🎉🎉🎉

**Review by TimCanu — APPROVED** [review]
Looks good but I did not test it. I can if you want but I'm confident that there is no need.

**Pull request merged**
