### PR TITLE
Added npm script to run both unit and integration tests (yourloops package)

### PR DESCRIPTION
**Pull request by TimCanu**

### CODE REVIEW

**Review by fatb38 — COMMENTED** [review]
Now with tests splitted in two, how can we distinguish coverage between unit and integration ? At the moment, if I run integration tests, we have a very low coverage, however many of the files are already tested in unit tests.

**Comment by Nas84** [comment]
a solution could be to merge the coverage reports, [https://stackoverflow.com/a/63008134/2000548](https://stackoverflow.com/a/63008134/2000548)

**Comment by TimCanu** [comment]
@fatb38 @Nas84  I don't know what are the benefits of merging the two coverages. Last discussions about testing ended up with the conclusion that unit tests were to cover the logic and custom hooks, whereas integration tests were about testing the dom of a page. Is there value in merging both? Can't it leads to confusion by seeing logic code that is covered by integration test when it has not been tested with unit tests?

**Review by fatb38 — APPROVED** [review]

**Comment by fatb38** [comment]
Script added in [PR 895](https://github.com/mdblp/blip/pull/895)

**Pull request closed without merging**
